# PYTHIA configuration file.
# Generated on Fri Mar 22 10:29:40 CDT 2024 with the user supplied options:
# --prefix=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/tmp/BUILDROOT/97646d8095752c6e96f84bb0257efff7/opt/cmssw/slc7_amd64_gcc700/external/pythia8/240-97646d8095752c6e96f84bb0257efff7
# --enable-shared
# --with-hepmc2=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/hepmc/2.06.07-pafccj
# --with-lhapdf6=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/lhapdf/6.2.3-a2a84f5990d32c24c7240b02577bf55e

# Install directory prefixes.
PREFIX_BIN=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/tmp/BUILDROOT/97646d8095752c6e96f84bb0257efff7/opt/cmssw/slc7_amd64_gcc700/external/pythia8/240-97646d8095752c6e96f84bb0257efff7/bin
PREFIX_INCLUDE=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/tmp/BUILDROOT/97646d8095752c6e96f84bb0257efff7/opt/cmssw/slc7_amd64_gcc700/external/pythia8/240-97646d8095752c6e96f84bb0257efff7/include
PREFIX_LIB=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/tmp/BUILDROOT/97646d8095752c6e96f84bb0257efff7/opt/cmssw/slc7_amd64_gcc700/external/pythia8/240-97646d8095752c6e96f84bb0257efff7/lib
PREFIX_SHARE=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/tmp/BUILDROOT/97646d8095752c6e96f84bb0257efff7/opt/cmssw/slc7_amd64_gcc700/external/pythia8/240-97646d8095752c6e96f84bb0257efff7/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=true
CXX=g++
CXX_COMMON=-O2  -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=
FASTJET3_LIB=

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/hepmc/2.06.07-pafccj/bin
HEPMC2_INCLUDE=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/hepmc/2.06.07-pafccj/include
HEPMC2_LIB=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/hepmc/2.06.07-pafccj/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=

# LHAPDF6 configuration.
LHAPDF6_USE=true
LHAPDF6_BIN=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/lhapdf/6.2.3-a2a84f5990d32c24c7240b02577bf55e/bin
LHAPDF6_INCLUDE=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/lhapdf/6.2.3-a2a84f5990d32c24c7240b02577bf55e/include
LHAPDF6_LIB=/work/build/CMSSW_10_6_X/slc7_amd64_gcc700/tmp/slc7_amd64_gcc700/external/lhapdf/6.2.3-a2a84f5990d32c24c7240b02577bf55e/lib

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=false
ROOT_BIN=
ROOT_LIBS=
CXX_ROOT=

# GZIP configuration.
GZIP_USE=false
GZIP_BIN=
GZIP_INCLUDE=
GZIP_LIB=

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=
BOOST_LIB=

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=
PYTHON_LIB=
